### ISSUE TITLE
_id系のString→Integer化の修正するときにSchema直接いじってない？

### ISSUE THREAD

**Issue by HirokiDaido** [biga816/mecasii#4]
マイグレーションファイルを作ってやらないと、Schema.rbは上書きされちゃうよ。

例
1.rails g migration changeIdColumnToString

2.できたマイグレーションファイル内で
change_column :table_name, :column_name,  :integer
を繰り返す

3. bundle exec rake db:migrate

**Comment by biga816** [comment]
すでにあるマイグレーションファイルを直接いじって「rake db:migrate:reset！！」って感じで再構築してました。
あまりこの方法はよろしくない感じ？

**Comment by HirokiDaido** [comment]
それでもOK!
ただ以下の場合はやめたほうがいいっすね
・本番ローンチ後
　→既存データ消える
・でっかいチームの場合
　→チームへの通知が面倒
